"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from datetime import date
from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

from wonde.api_client import ApiClient, RequestSerialized
from wonde.api_response import ApiResponse
from wonde.models.employee import Employee
from wonde.models.list_school_employees200_response import ListSchoolEmployees200Response
from wonde.rest import RESTResponseType


class EmployeesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_school_employee(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school')],
        employee_id: Annotated[StrictStr, Field(description='The ID of the employee')],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Employee:
        """Get specific employee for a school

        You need the employees read permission to view this object. To retrieve the secondary and tertiary ids please add extra_ids=true to the url.

        :param school_id: The ID of the school (required)
        :type school_id: str
        :param employee_id: The ID of the employee (required)
        :type employee_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._get_school_employee_serialize(
            school_id=school_id,
            employee_id=employee_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'Employee',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_school_employee_with_http_info(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school')],
        employee_id: Annotated[StrictStr, Field(description='The ID of the employee')],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Employee]:
        """Get specific employee for a school

        You need the employees read permission to view this object. To retrieve the secondary and tertiary ids please add extra_ids=true to the url.

        :param school_id: The ID of the school (required)
        :type school_id: str
        :param employee_id: The ID of the employee (required)
        :type employee_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._get_school_employee_serialize(
            school_id=school_id,
            employee_id=employee_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'Employee',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_school_employee_without_preload_content(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school')],
        employee_id: Annotated[StrictStr, Field(description='The ID of the employee')],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get specific employee for a school

        You need the employees read permission to view this object. To retrieve the secondary and tertiary ids please add extra_ids=true to the url.

        :param school_id: The ID of the school (required)
        :type school_id: str
        :param employee_id: The ID of the employee (required)
        :type employee_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._get_school_employee_serialize(
            school_id=school_id,
            employee_id=employee_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'Employee',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _get_school_employee_serialize(
        self,
        school_id,
        employee_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if school_id is not None:
            _path_params['school_id'] = school_id
        if employee_id is not None:
            _path_params['employee_id'] = employee_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['BasicAuth', 'BearerAuth']

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/schools/{school_id}/employees/{employee_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def list_school_employees(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school')],
        updated_after: Annotated[
            Optional[date], Field(description='Return rows modified after date')
        ] = None,
        updated_before: Annotated[
            Optional[date], Field(description='Return rows modified before date')
        ] = None,
        per_page: Annotated[
            Optional[StrictInt], Field(description='Amount of rows to return')
        ] = None,
        page: Annotated[
            Optional[StrictInt], Field(description='Page offset for offset-paginated results.')
        ] = None,
        cursor: Annotated[
            Optional[StrictStr], Field(description='Page cursor for cursor-paginated results.')
        ] = None,
        include: Annotated[
            Optional[StrictStr], Field(description='Comma separated list of objects to include')
        ] = None,
        employment_start_before: Annotated[
            Optional[date], Field(description='Get employees who have started before a date')
        ] = None,
        employment_start_after: Annotated[
            Optional[date], Field(description='Get employees who have started after a date')
        ] = None,
        has_role: Annotated[
            Optional[StrictBool], Field(description='Only return employees that have a role')
        ] = None,
        has_contract: Annotated[
            Optional[StrictBool], Field(description='Only return employees that have a contract')
        ] = None,
        has_class: Annotated[
            Optional[StrictBool],
            Field(description='Only return employees that have one or more classes'),
        ] = None,
        has_group: Annotated[
            Optional[StrictBool],
            Field(description='Only return employees that have one or more groups'),
        ] = None,
        user_defined_field: Annotated[
            Optional[StrictStr], Field(description='Filter employees by user defined field key')
        ] = None,
        only_user_defined_fields: Annotated[
            Optional[StrictStr],
            Field(description='Filter user defined fields by comma separated list'),
        ] = None,
        only_mis_ids: Annotated[
            Optional[StrictStr], Field(description='Filter MIS ids by comma separated list')
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListSchoolEmployees200Response:
        """Get all employees for a school


        :param school_id: The ID of the school (required)
        :type school_id: str
        :param updated_after: Return rows modified after date
        :type updated_after: date
        :param updated_before: Return rows modified before date
        :type updated_before: date
        :param per_page: Amount of rows to return
        :type per_page: int
        :param page: Page offset for offset-paginated results.
        :type page: int
        :param cursor: Page cursor for cursor-paginated results.
        :type cursor: str
        :param include: Comma separated list of objects to include
        :type include: str
        :param employment_start_before: Get employees who have started before a date
        :type employment_start_before: date
        :param employment_start_after: Get employees who have started after a date
        :type employment_start_after: date
        :param has_role: Only return employees that have a role
        :type has_role: bool
        :param has_contract: Only return employees that have a contract
        :type has_contract: bool
        :param has_class: Only return employees that have one or more classes
        :type has_class: bool
        :param has_group: Only return employees that have one or more groups
        :type has_group: bool
        :param user_defined_field: Filter employees by user defined field key
        :type user_defined_field: str
        :param only_user_defined_fields: Filter user defined fields by comma separated list
        :type only_user_defined_fields: str
        :param only_mis_ids: Filter MIS ids by comma separated list
        :type only_mis_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._list_school_employees_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            per_page=per_page,
            page=page,
            cursor=cursor,
            include=include,
            employment_start_before=employment_start_before,
            employment_start_after=employment_start_after,
            has_role=has_role,
            has_contract=has_contract,
            has_class=has_class,
            has_group=has_group,
            user_defined_field=user_defined_field,
            only_user_defined_fields=only_user_defined_fields,
            only_mis_ids=only_mis_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ListSchoolEmployees200Response',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def list_school_employees_with_http_info(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school')],
        updated_after: Annotated[
            Optional[date], Field(description='Return rows modified after date')
        ] = None,
        updated_before: Annotated[
            Optional[date], Field(description='Return rows modified before date')
        ] = None,
        per_page: Annotated[
            Optional[StrictInt], Field(description='Amount of rows to return')
        ] = None,
        page: Annotated[
            Optional[StrictInt], Field(description='Page offset for offset-paginated results.')
        ] = None,
        cursor: Annotated[
            Optional[StrictStr], Field(description='Page cursor for cursor-paginated results.')
        ] = None,
        include: Annotated[
            Optional[StrictStr], Field(description='Comma separated list of objects to include')
        ] = None,
        employment_start_before: Annotated[
            Optional[date], Field(description='Get employees who have started before a date')
        ] = None,
        employment_start_after: Annotated[
            Optional[date], Field(description='Get employees who have started after a date')
        ] = None,
        has_role: Annotated[
            Optional[StrictBool], Field(description='Only return employees that have a role')
        ] = None,
        has_contract: Annotated[
            Optional[StrictBool], Field(description='Only return employees that have a contract')
        ] = None,
        has_class: Annotated[
            Optional[StrictBool],
            Field(description='Only return employees that have one or more classes'),
        ] = None,
        has_group: Annotated[
            Optional[StrictBool],
            Field(description='Only return employees that have one or more groups'),
        ] = None,
        user_defined_field: Annotated[
            Optional[StrictStr], Field(description='Filter employees by user defined field key')
        ] = None,
        only_user_defined_fields: Annotated[
            Optional[StrictStr],
            Field(description='Filter user defined fields by comma separated list'),
        ] = None,
        only_mis_ids: Annotated[
            Optional[StrictStr], Field(description='Filter MIS ids by comma separated list')
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListSchoolEmployees200Response]:
        """Get all employees for a school


        :param school_id: The ID of the school (required)
        :type school_id: str
        :param updated_after: Return rows modified after date
        :type updated_after: date
        :param updated_before: Return rows modified before date
        :type updated_before: date
        :param per_page: Amount of rows to return
        :type per_page: int
        :param page: Page offset for offset-paginated results.
        :type page: int
        :param cursor: Page cursor for cursor-paginated results.
        :type cursor: str
        :param include: Comma separated list of objects to include
        :type include: str
        :param employment_start_before: Get employees who have started before a date
        :type employment_start_before: date
        :param employment_start_after: Get employees who have started after a date
        :type employment_start_after: date
        :param has_role: Only return employees that have a role
        :type has_role: bool
        :param has_contract: Only return employees that have a contract
        :type has_contract: bool
        :param has_class: Only return employees that have one or more classes
        :type has_class: bool
        :param has_group: Only return employees that have one or more groups
        :type has_group: bool
        :param user_defined_field: Filter employees by user defined field key
        :type user_defined_field: str
        :param only_user_defined_fields: Filter user defined fields by comma separated list
        :type only_user_defined_fields: str
        :param only_mis_ids: Filter MIS ids by comma separated list
        :type only_mis_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._list_school_employees_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            per_page=per_page,
            page=page,
            cursor=cursor,
            include=include,
            employment_start_before=employment_start_before,
            employment_start_after=employment_start_after,
            has_role=has_role,
            has_contract=has_contract,
            has_class=has_class,
            has_group=has_group,
            user_defined_field=user_defined_field,
            only_user_defined_fields=only_user_defined_fields,
            only_mis_ids=only_mis_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ListSchoolEmployees200Response',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def list_school_employees_without_preload_content(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school')],
        updated_after: Annotated[
            Optional[date], Field(description='Return rows modified after date')
        ] = None,
        updated_before: Annotated[
            Optional[date], Field(description='Return rows modified before date')
        ] = None,
        per_page: Annotated[
            Optional[StrictInt], Field(description='Amount of rows to return')
        ] = None,
        page: Annotated[
            Optional[StrictInt], Field(description='Page offset for offset-paginated results.')
        ] = None,
        cursor: Annotated[
            Optional[StrictStr], Field(description='Page cursor for cursor-paginated results.')
        ] = None,
        include: Annotated[
            Optional[StrictStr], Field(description='Comma separated list of objects to include')
        ] = None,
        employment_start_before: Annotated[
            Optional[date], Field(description='Get employees who have started before a date')
        ] = None,
        employment_start_after: Annotated[
            Optional[date], Field(description='Get employees who have started after a date')
        ] = None,
        has_role: Annotated[
            Optional[StrictBool], Field(description='Only return employees that have a role')
        ] = None,
        has_contract: Annotated[
            Optional[StrictBool], Field(description='Only return employees that have a contract')
        ] = None,
        has_class: Annotated[
            Optional[StrictBool],
            Field(description='Only return employees that have one or more classes'),
        ] = None,
        has_group: Annotated[
            Optional[StrictBool],
            Field(description='Only return employees that have one or more groups'),
        ] = None,
        user_defined_field: Annotated[
            Optional[StrictStr], Field(description='Filter employees by user defined field key')
        ] = None,
        only_user_defined_fields: Annotated[
            Optional[StrictStr],
            Field(description='Filter user defined fields by comma separated list'),
        ] = None,
        only_mis_ids: Annotated[
            Optional[StrictStr], Field(description='Filter MIS ids by comma separated list')
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get all employees for a school


        :param school_id: The ID of the school (required)
        :type school_id: str
        :param updated_after: Return rows modified after date
        :type updated_after: date
        :param updated_before: Return rows modified before date
        :type updated_before: date
        :param per_page: Amount of rows to return
        :type per_page: int
        :param page: Page offset for offset-paginated results.
        :type page: int
        :param cursor: Page cursor for cursor-paginated results.
        :type cursor: str
        :param include: Comma separated list of objects to include
        :type include: str
        :param employment_start_before: Get employees who have started before a date
        :type employment_start_before: date
        :param employment_start_after: Get employees who have started after a date
        :type employment_start_after: date
        :param has_role: Only return employees that have a role
        :type has_role: bool
        :param has_contract: Only return employees that have a contract
        :type has_contract: bool
        :param has_class: Only return employees that have one or more classes
        :type has_class: bool
        :param has_group: Only return employees that have one or more groups
        :type has_group: bool
        :param user_defined_field: Filter employees by user defined field key
        :type user_defined_field: str
        :param only_user_defined_fields: Filter user defined fields by comma separated list
        :type only_user_defined_fields: str
        :param only_mis_ids: Filter MIS ids by comma separated list
        :type only_mis_ids: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._list_school_employees_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            per_page=per_page,
            page=page,
            cursor=cursor,
            include=include,
            employment_start_before=employment_start_before,
            employment_start_after=employment_start_after,
            has_role=has_role,
            has_contract=has_contract,
            has_class=has_class,
            has_group=has_group,
            user_defined_field=user_defined_field,
            only_user_defined_fields=only_user_defined_fields,
            only_mis_ids=only_mis_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ListSchoolEmployees200Response',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _list_school_employees_serialize(
        self,
        school_id,
        updated_after,
        updated_before,
        per_page,
        page,
        cursor,
        include,
        employment_start_before,
        employment_start_after,
        has_role,
        has_contract,
        has_class,
        has_group,
        user_defined_field,
        only_user_defined_fields,
        only_mis_ids,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if school_id is not None:
            _path_params['school_id'] = school_id
        # process the query parameters
        if updated_after is not None:
            if isinstance(updated_after, date):
                _query_params.append(
                    (
                        'updated_after',
                        updated_after.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('updated_after', updated_after))

        if updated_before is not None:
            if isinstance(updated_before, date):
                _query_params.append(
                    (
                        'updated_before',
                        updated_before.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('updated_before', updated_before))

        if per_page is not None:

            _query_params.append(('per_page', per_page))

        if page is not None:

            _query_params.append(('page', page))

        if cursor is not None:

            _query_params.append(('cursor', cursor))

        if include is not None:

            _query_params.append(('include', include))

        if employment_start_before is not None:
            if isinstance(employment_start_before, date):
                _query_params.append(
                    (
                        'employment_start_before',
                        employment_start_before.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('employment_start_before', employment_start_before))

        if employment_start_after is not None:
            if isinstance(employment_start_after, date):
                _query_params.append(
                    (
                        'employment_start_after',
                        employment_start_after.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('employment_start_after', employment_start_after))

        if has_role is not None:

            _query_params.append(('has_role', has_role))

        if has_contract is not None:

            _query_params.append(('has_contract', has_contract))

        if has_class is not None:

            _query_params.append(('has_class', has_class))

        if has_group is not None:

            _query_params.append(('has_group', has_group))

        if user_defined_field is not None:

            _query_params.append(('user_defined_field', user_defined_field))

        if only_user_defined_fields is not None:

            _query_params.append(('only_user_defined_fields', only_user_defined_fields))

        if only_mis_ids is not None:

            _query_params.append(('only_mis_ids', only_mis_ids))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['BasicAuth', 'BearerAuth']

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/schools/{school_id}/employees',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
