"""
    Wonde API

    API Docs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from wonde.models.list_school_groups200_response import ListSchoolGroups200Response

from wonde.api_client import ApiClient, RequestSerialized
from wonde.api_response import ApiResponse
from wonde.rest import RESTResponseType


class GroupsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_school_groups(
        self,
        school_id: Annotated[StrictStr, Field(description="The ID of the school")],
        updated_after: Annotated[Optional[date], Field(description="Return rows modified after date")] = None,
        updated_before: Annotated[Optional[date], Field(description="Return rows modified before date")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Amount of rows to return")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page offset for offset-paginated results.")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Page cursor for cursor-paginated results.")] = None,
        include: Annotated[Optional[StrictStr], Field(description="Comma separated list of objects to include")] = None,
        type: Annotated[Optional[StrictStr], Field(description="Only return groups with the provided type. One of REGISTRATION, YEAR, HOUSE, BOARDING, COURSE, MISC, USER, CAMPUS, DIVISION, DEPARTMENT. ")] = None,
        has_students: Annotated[Optional[StrictBool], Field(description="Only return groups that have students")] = None,
        has_employees: Annotated[Optional[StrictBool], Field(description="Only return groups that have employees")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListSchoolGroups200Response:
        """Get all groups for a school


        :param school_id: The ID of the school (required)
        :type school_id: str
        :param updated_after: Return rows modified after date
        :type updated_after: date
        :param updated_before: Return rows modified before date
        :type updated_before: date
        :param per_page: Amount of rows to return
        :type per_page: int
        :param page: Page offset for offset-paginated results.
        :type page: int
        :param cursor: Page cursor for cursor-paginated results.
        :type cursor: str
        :param include: Comma separated list of objects to include
        :type include: str
        :param type: Only return groups with the provided type. One of REGISTRATION, YEAR, HOUSE, BOARDING, COURSE, MISC, USER, CAMPUS, DIVISION, DEPARTMENT. 
        :type type: str
        :param has_students: Only return groups that have students
        :type has_students: bool
        :param has_employees: Only return groups that have employees
        :type has_employees: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_school_groups_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            per_page=per_page,
            page=page,
            cursor=cursor,
            include=include,
            type=type,
            has_students=has_students,
            has_employees=has_employees,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListSchoolGroups200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_school_groups_with_http_info(
        self,
        school_id: Annotated[StrictStr, Field(description="The ID of the school")],
        updated_after: Annotated[Optional[date], Field(description="Return rows modified after date")] = None,
        updated_before: Annotated[Optional[date], Field(description="Return rows modified before date")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Amount of rows to return")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page offset for offset-paginated results.")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Page cursor for cursor-paginated results.")] = None,
        include: Annotated[Optional[StrictStr], Field(description="Comma separated list of objects to include")] = None,
        type: Annotated[Optional[StrictStr], Field(description="Only return groups with the provided type. One of REGISTRATION, YEAR, HOUSE, BOARDING, COURSE, MISC, USER, CAMPUS, DIVISION, DEPARTMENT. ")] = None,
        has_students: Annotated[Optional[StrictBool], Field(description="Only return groups that have students")] = None,
        has_employees: Annotated[Optional[StrictBool], Field(description="Only return groups that have employees")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListSchoolGroups200Response]:
        """Get all groups for a school


        :param school_id: The ID of the school (required)
        :type school_id: str
        :param updated_after: Return rows modified after date
        :type updated_after: date
        :param updated_before: Return rows modified before date
        :type updated_before: date
        :param per_page: Amount of rows to return
        :type per_page: int
        :param page: Page offset for offset-paginated results.
        :type page: int
        :param cursor: Page cursor for cursor-paginated results.
        :type cursor: str
        :param include: Comma separated list of objects to include
        :type include: str
        :param type: Only return groups with the provided type. One of REGISTRATION, YEAR, HOUSE, BOARDING, COURSE, MISC, USER, CAMPUS, DIVISION, DEPARTMENT. 
        :type type: str
        :param has_students: Only return groups that have students
        :type has_students: bool
        :param has_employees: Only return groups that have employees
        :type has_employees: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_school_groups_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            per_page=per_page,
            page=page,
            cursor=cursor,
            include=include,
            type=type,
            has_students=has_students,
            has_employees=has_employees,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListSchoolGroups200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_school_groups_without_preload_content(
        self,
        school_id: Annotated[StrictStr, Field(description="The ID of the school")],
        updated_after: Annotated[Optional[date], Field(description="Return rows modified after date")] = None,
        updated_before: Annotated[Optional[date], Field(description="Return rows modified before date")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Amount of rows to return")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page offset for offset-paginated results.")] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="Page cursor for cursor-paginated results.")] = None,
        include: Annotated[Optional[StrictStr], Field(description="Comma separated list of objects to include")] = None,
        type: Annotated[Optional[StrictStr], Field(description="Only return groups with the provided type. One of REGISTRATION, YEAR, HOUSE, BOARDING, COURSE, MISC, USER, CAMPUS, DIVISION, DEPARTMENT. ")] = None,
        has_students: Annotated[Optional[StrictBool], Field(description="Only return groups that have students")] = None,
        has_employees: Annotated[Optional[StrictBool], Field(description="Only return groups that have employees")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get all groups for a school


        :param school_id: The ID of the school (required)
        :type school_id: str
        :param updated_after: Return rows modified after date
        :type updated_after: date
        :param updated_before: Return rows modified before date
        :type updated_before: date
        :param per_page: Amount of rows to return
        :type per_page: int
        :param page: Page offset for offset-paginated results.
        :type page: int
        :param cursor: Page cursor for cursor-paginated results.
        :type cursor: str
        :param include: Comma separated list of objects to include
        :type include: str
        :param type: Only return groups with the provided type. One of REGISTRATION, YEAR, HOUSE, BOARDING, COURSE, MISC, USER, CAMPUS, DIVISION, DEPARTMENT. 
        :type type: str
        :param has_students: Only return groups that have students
        :type has_students: bool
        :param has_employees: Only return groups that have employees
        :type has_employees: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_school_groups_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            per_page=per_page,
            page=page,
            cursor=cursor,
            include=include,
            type=type,
            has_students=has_students,
            has_employees=has_employees,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListSchoolGroups200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_school_groups_serialize(
        self,
        school_id,
        updated_after,
        updated_before,
        per_page,
        page,
        cursor,
        include,
        type,
        has_students,
        has_employees,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if school_id is not None:
            _path_params['school_id'] = school_id
        # process the query parameters
        if updated_after is not None:
            if isinstance(updated_after, date):
                _query_params.append(
                    (
                        'updated_after',
                        updated_after.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_after', updated_after))
            
        if updated_before is not None:
            if isinstance(updated_before, date):
                _query_params.append(
                    (
                        'updated_before',
                        updated_before.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_before', updated_before))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        if has_students is not None:
            
            _query_params.append(('has_students', has_students))
            
        if has_employees is not None:
            
            _query_params.append(('has_employees', has_employees))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BasicAuth', 
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/schools/{school_id}/groups',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


