"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from datetime import date
from typing import Any, Dict, List, Optional, Tuple, Union

from pydantic import Field, StrictFloat, StrictInt, StrictStr, validate_call
from typing_extensions import Annotated

from wonde.api_client import ApiClient, RequestSerialized
from wonde.api_response import ApiResponse
from wonde.models.lesson import Lesson
from wonde.models.list_school_lessons200_response import ListSchoolLessons200Response
from wonde.rest import RESTResponseType


class LessonsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def get_school_lesson(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school.')],
        lesson_id: Annotated[StrictStr, Field(description='The ID of the lesson.')],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Lesson:
        """Returns a specific lesson for a specific school


        :param school_id: The ID of the school. (required)
        :type school_id: str
        :param lesson_id: The ID of the lesson. (required)
        :type lesson_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._get_school_lesson_serialize(
            school_id=school_id,
            lesson_id=lesson_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'Lesson',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_school_lesson_with_http_info(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school.')],
        lesson_id: Annotated[StrictStr, Field(description='The ID of the lesson.')],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Lesson]:
        """Returns a specific lesson for a specific school


        :param school_id: The ID of the school. (required)
        :type school_id: str
        :param lesson_id: The ID of the lesson. (required)
        :type lesson_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._get_school_lesson_serialize(
            school_id=school_id,
            lesson_id=lesson_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'Lesson',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_school_lesson_without_preload_content(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school.')],
        lesson_id: Annotated[StrictStr, Field(description='The ID of the lesson.')],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a specific lesson for a specific school


        :param school_id: The ID of the school. (required)
        :type school_id: str
        :param lesson_id: The ID of the lesson. (required)
        :type lesson_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._get_school_lesson_serialize(
            school_id=school_id,
            lesson_id=lesson_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'Lesson',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _get_school_lesson_serialize(
        self,
        school_id,
        lesson_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if school_id is not None:
            _path_params['school_id'] = school_id
        if lesson_id is not None:
            _path_params['lesson_id'] = lesson_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['BasicAuth', 'BearerAuth']

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/schools/{school_id}/lessons/{lesson_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def list_school_lessons(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school.')],
        updated_after: Annotated[
            Optional[date], Field(description='Return rows modified after date.')
        ] = None,
        updated_before: Annotated[
            Optional[date], Field(description='Return rows modified before date.')
        ] = None,
        lessons_start_after: Annotated[
            Optional[date], Field(description='Return rows starting after date.')
        ] = None,
        lessons_start_before: Annotated[
            Optional[date], Field(description='Return rows starting before date.')
        ] = None,
        per_page: Annotated[
            Optional[StrictInt], Field(description='Amount of rows to return.')
        ] = None,
        include: Annotated[
            Optional[StrictStr], Field(description='Comma separated list of objects to include.')
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListSchoolLessons200Response:
        """Returns a list of lessons for a specific school


        :param school_id: The ID of the school. (required)
        :type school_id: str
        :param updated_after: Return rows modified after date.
        :type updated_after: date
        :param updated_before: Return rows modified before date.
        :type updated_before: date
        :param lessons_start_after: Return rows starting after date.
        :type lessons_start_after: date
        :param lessons_start_before: Return rows starting before date.
        :type lessons_start_before: date
        :param per_page: Amount of rows to return.
        :type per_page: int
        :param include: Comma separated list of objects to include.
        :type include: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._list_school_lessons_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            lessons_start_after=lessons_start_after,
            lessons_start_before=lessons_start_before,
            per_page=per_page,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ListSchoolLessons200Response',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def list_school_lessons_with_http_info(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school.')],
        updated_after: Annotated[
            Optional[date], Field(description='Return rows modified after date.')
        ] = None,
        updated_before: Annotated[
            Optional[date], Field(description='Return rows modified before date.')
        ] = None,
        lessons_start_after: Annotated[
            Optional[date], Field(description='Return rows starting after date.')
        ] = None,
        lessons_start_before: Annotated[
            Optional[date], Field(description='Return rows starting before date.')
        ] = None,
        per_page: Annotated[
            Optional[StrictInt], Field(description='Amount of rows to return.')
        ] = None,
        include: Annotated[
            Optional[StrictStr], Field(description='Comma separated list of objects to include.')
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListSchoolLessons200Response]:
        """Returns a list of lessons for a specific school


        :param school_id: The ID of the school. (required)
        :type school_id: str
        :param updated_after: Return rows modified after date.
        :type updated_after: date
        :param updated_before: Return rows modified before date.
        :type updated_before: date
        :param lessons_start_after: Return rows starting after date.
        :type lessons_start_after: date
        :param lessons_start_before: Return rows starting before date.
        :type lessons_start_before: date
        :param per_page: Amount of rows to return.
        :type per_page: int
        :param include: Comma separated list of objects to include.
        :type include: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._list_school_lessons_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            lessons_start_after=lessons_start_after,
            lessons_start_before=lessons_start_before,
            per_page=per_page,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ListSchoolLessons200Response',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def list_school_lessons_without_preload_content(
        self,
        school_id: Annotated[StrictStr, Field(description='The ID of the school.')],
        updated_after: Annotated[
            Optional[date], Field(description='Return rows modified after date.')
        ] = None,
        updated_before: Annotated[
            Optional[date], Field(description='Return rows modified before date.')
        ] = None,
        lessons_start_after: Annotated[
            Optional[date], Field(description='Return rows starting after date.')
        ] = None,
        lessons_start_before: Annotated[
            Optional[date], Field(description='Return rows starting before date.')
        ] = None,
        per_page: Annotated[
            Optional[StrictInt], Field(description='Amount of rows to return.')
        ] = None,
        include: Annotated[
            Optional[StrictStr], Field(description='Comma separated list of objects to include.')
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a list of lessons for a specific school


        :param school_id: The ID of the school. (required)
        :type school_id: str
        :param updated_after: Return rows modified after date.
        :type updated_after: date
        :param updated_before: Return rows modified before date.
        :type updated_before: date
        :param lessons_start_after: Return rows starting after date.
        :type lessons_start_after: date
        :param lessons_start_before: Return rows starting before date.
        :type lessons_start_before: date
        :param per_page: Amount of rows to return.
        :type per_page: int
        :param include: Comma separated list of objects to include.
        :type include: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """

        _param = self._list_school_lessons_serialize(
            school_id=school_id,
            updated_after=updated_after,
            updated_before=updated_before,
            lessons_start_after=lessons_start_after,
            lessons_start_before=lessons_start_before,
            per_page=per_page,
            include=include,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': 'ListSchoolLessons200Response',
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _list_school_lessons_serialize(
        self,
        school_id,
        updated_after,
        updated_before,
        lessons_start_after,
        lessons_start_before,
        per_page,
        include,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if school_id is not None:
            _path_params['school_id'] = school_id
        # process the query parameters
        if updated_after is not None:
            if isinstance(updated_after, date):
                _query_params.append(
                    (
                        'updated_after',
                        updated_after.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('updated_after', updated_after))

        if updated_before is not None:
            if isinstance(updated_before, date):
                _query_params.append(
                    (
                        'updated_before',
                        updated_before.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('updated_before', updated_before))

        if lessons_start_after is not None:
            if isinstance(lessons_start_after, date):
                _query_params.append(
                    (
                        'lessons_start_after',
                        lessons_start_after.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('lessons_start_after', lessons_start_after))

        if lessons_start_before is not None:
            if isinstance(lessons_start_before, date):
                _query_params.append(
                    (
                        'lessons_start_before',
                        lessons_start_before.strftime(self.api_client.configuration.date_format),
                    )
                )
            else:
                _query_params.append(('lessons_start_before', lessons_start_before))

        if per_page is not None:

            _query_params.append(('per_page', per_page))

        if include is not None:

            _query_params.append(('include', include))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(['application/json'])

        # authentication setting
        _auth_settings: List[str] = ['BasicAuth', 'BearerAuth']

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/schools/{school_id}/lessons',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
