"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest


class TestClassLessons(unittest.TestCase):
    """ClassLessons unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClassLessons
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ClassLessons`
        """
        model = wonde.models.class_lessons.ClassLessons()  # noqa: E501
        if include_optional :
            return ClassLessons(
                data = [
                    wonde.models.lesson.Lesson(
                        id = '', 
                        room = '', 
                        period = '', 
                        employee_id = '', 
                        period_instance_id = 56, 
                        alternative = True, 
                        start_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        end_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        created_at = , 
                        updated_at = , )
                    ]
            )
        else :
            return ClassLessons(
        )
        """

    def testClassLessons(self):
        """Test ClassLessons"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
