# coding: utf-8

"""
    Wonde API

    API Docs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wonde.models.employee_contact_details import EmployeeContactDetails  # noqa: E501

class TestEmployeeContactDetails(unittest.TestCase):
    """EmployeeContactDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmployeeContactDetails:
        """Test EmployeeContactDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmployeeContactDetails`
        """
        model = EmployeeContactDetails()  # noqa: E501
        if include_optional:
            return EmployeeContactDetails(
                data = wonde.models.contact_details.ContactDetails(
                    emails = wonde.models.contact_details_emails.ContactDetails_emails(
                        email = '', ), )
            )
        else:
            return EmployeeContactDetails(
        )
        """

    def testEmployeeContactDetails(self):
        """Test EmployeeContactDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
