"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.api.classes_api import ClassesApi


class TestClassesApi(unittest.TestCase):
    """ClassesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClassesApi()

    def tearDown(self) -> None:
        pass

    def test_get_school_class(self) -> None:
        """Test case for get_school_class

        Get specific class for a school  # noqa: E501
        """
        pass

    def test_list_school_classes(self) -> None:
        """Test case for list_school_classes

        Get all classes for a school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
