"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.api.students_api import StudentsApi


class TestStudentsApi(unittest.TestCase):
    """StudentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StudentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_school_student(self) -> None:
        """Test case for get_school_student

        Retrieve a specific student in a specific school  # noqa: E501
        """
        pass

    def test_list_school_students(self) -> None:
        """Test case for list_school_students

        Retrieve a list of students for a specific school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
