"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

import wonde


class TestSubjectsApi(unittest.TestCase):
    """SubjectsApi unit test stubs"""

    def setUp(self):
        self.api = wonde.api.subjects_api.SubjectsApi()

    def tearDown(self):
        pass

    def test_get_subject(self):
        """Test case for get_subject

        Retrieve a specific subject for a school  # noqa: E501
        """
        pass

    def test_get_subjects(self):
        """Test case for get_subjects

        Retrieve subjects for a school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
