# coding: utf-8

"""
    Wonde API

    API Docs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from wonde.models.education_details import EducationDetails  # noqa: E501

class TestEducationDetails(unittest.TestCase):
    """EducationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EducationDetails:
        """Test EducationDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EducationDetails`
        """
        model = EducationDetails()  # noqa: E501
        if include_optional:
            return EducationDetails(
                current_nc_year = '',
                local_upn = ''
            )
        else:
            return EducationDetails(
        )
        """

    def testEducationDetails(self):
        """Test EducationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
