# coding: utf-8

"""
    Wonde API

    API Docs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wonde.models.list_school_groups200_response import ListSchoolGroups200Response

class TestListSchoolGroups200Response(unittest.TestCase):
    """ListSchoolGroups200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSchoolGroups200Response:
        """Test ListSchoolGroups200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSchoolGroups200Response`
        """
        model = ListSchoolGroups200Response()
        if include_optional:
            return ListSchoolGroups200Response(
                data = [
                    wonde.models.group.Group(
                        id = 'A1161584171', 
                        mis_id = '425', 
                        name = '10A', 
                        code = '10A', 
                        type = 'REGISTRATION', 
                        description = '', 
                        notes = '', 
                        restored_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        created_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        updated_at = , 
                        students = wonde.models.school_class_students.SchoolClass_students(
                            data = [
                                wonde.models.student.Student(
                                    id = 'A1749191433', 
                                    upi = '8d444684b7aa79bc97f8594a4aab7ce3', 
                                    mis_id = '9919', 
                                    title = 'Mr', 
                                    initials = 'TS', 
                                    surname = 'Smith', 
                                    forename = 'Tom', 
                                    middle_names = '', 
                                    legal_surname = 'Smith', 
                                    legal_forename = 'Tom', 
                                    gender = 'male', 
                                    gender_identity = '', 
                                    date_of_birth = 'Thu Feb 11 00:00:00 UTC 2010', 
                                    contact_details = wonde.models.employee_contact_details.Employee_contact_details(), 
                                    education_details = wonde.models.student_education_details.Student_education_details(), )
                                ], ), 
                        employees = wonde.models.school_class_employees.SchoolClass_employees(), )
                    ],
                meta = wonde.models.meta.Meta(
                    pagination = wonde.models.pagination.Pagination(
                        next = 'https://api.wonde.com/v1.0/schools/{school_id}/students/?page=2', 
                        previous = '', 
                        more = True, 
                        per_page = 2, 
                        current_page = 1, ), 
                    includes = [
                        ''
                        ], )
            )
        else:
            return ListSchoolGroups200Response(
        )
        """

    def testListSchoolGroups200Response(self):
        """Test ListSchoolGroups200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
