# coding: utf-8

"""
    Wonde API

    API Docs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from wonde.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_list_school_groups(self) -> None:
        """Test case for list_school_groups

        Get all groups for a school
        """
        pass


if __name__ == '__main__':
    unittest.main()
