"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.get_school_class200_response import GetSchoolClass200Response


class TestGetSchoolClass200Response(unittest.TestCase):
    """GetSchoolClass200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSchoolClass200Response:
        """Test GetSchoolClass200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetSchoolClass200Response`
        """
        model = GetSchoolClass200Response()  # noqa: E501
        if include_optional:
            return GetSchoolClass200Response(
                data = wonde.models.school_class.SchoolClass(
                    id = 'A1329183376', 
                    mis_id = '8925', 
                    name = '10A/Ar1', 
                    code = '10A/Ar1', 
                    description = '10A/Ar1', 
                    subject = null, 
                    alternative = False, 
                    restored_at = wonde.models.date_time_object.DateTimeObject(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        timezone_type = 3, 
                        timezone = 'UTC', ), 
                    created_at = wonde.models.date_time_object.DateTimeObject(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        timezone_type = 3, 
                        timezone = 'UTC', ), 
                    updated_at = , 
                    students = wonde.models.school_class_students.SchoolClass_students(
                        data = [
                            wonde.models.student.Student(
                                id = 'A1749191433', 
                                upi = '8d444684b7aa79bc97f8594a4aab7ce3', 
                                mis_id = '9919', 
                                initials = 'TS', 
                                surname = 'Smith', 
                                forename = 'Tom', 
                                middle_names = '', 
                                legal_surname = 'Smith', 
                                legal_forename = 'Tom', 
                                gender = 'MALE', 
                                date_of_birth = 'Thu Feb 11 00:00:00 UTC 2010', 
                                contact_details = wonde.models.employee_contact_details.Employee_contact_details(), 
                                education_details = wonde.models.student_education_details.Student_education_details(), )
                            ], ), 
                    employees = wonde.models.school_class_employees.SchoolClass_employees(), 
                    lessons = wonde.models.school_class_lessons.SchoolClass_lessons(), ),
                meta = wonde.models.meta.Meta(
                    pagination = wonde.models.pagination.Pagination(
                        next = 'https://api.wonde.com/v1.0/schools/{school_id}/students/?page=2', 
                        previous = '', 
                        more = True, 
                        per_page = 2, 
                        current_page = 1, ), 
                    includes = [
                        ''
                        ], )
            )
        else:
            return GetSchoolClass200Response(
        )
        """

    def testGetSchoolClass200Response(self):
        """Test GetSchoolClass200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
