"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.list_school_employees200_response import (
    ListSchoolEmployees200Response,
)


class TestListSchoolEmployees200Response(unittest.TestCase):
    """ListSchoolEmployees200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSchoolEmployees200Response:
        """Test ListSchoolEmployees200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListSchoolEmployees200Response`
        """
        model = ListSchoolEmployees200Response()  # noqa: E501
        if include_optional:
            return ListSchoolEmployees200Response(
                data = [
                    wonde.models.employee.Employee(
                        id = 'A1329183376', 
                        upi = '5cc4ab015f8f7870b581e30e0ef474fa', 
                        mis_id = '26', 
                        title = 'Mrs', 
                        initials = 'SS', 
                        surname = 'Smith', 
                        forename = 'Sally', 
                        middle_names = 'Victoria', 
                        legal_surname = 'Smith', 
                        legal_forename = 'Sally', 
                        gender = 'female', 
                        date_of_birth = 'Mon Feb 11 00:00:00 UTC 1963', 
                        restored_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        created_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        updated_at = , 
                        contact_details = wonde.models.employee_contact_details.Employee_contact_details(
                            data = wonde.models.contact_details.ContactDetails(
                                emails = wonde.models.contact_details_emails.ContactDetails_emails(
                                    email = '', ), ), ), )
                    ],
                meta = wonde.models.meta.Meta(
                    pagination = wonde.models.pagination.Pagination(
                        next = 'https://api.wonde.com/v1.0/schools/{school_id}/students/?page=2', 
                        previous = '', 
                        more = True, 
                        per_page = 2, 
                        current_page = 1, ), 
                    includes = [
                        ''
                        ], )
            )
        else:
            return ListSchoolEmployees200Response(
        )
        """

    def testListSchoolEmployees200Response(self):
        """Test ListSchoolEmployees200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
