"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.school import School


class TestSchool(unittest.TestCase):
    """School unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> School:
        """Test School
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `School`
        """
        model = School()  # noqa: E501
        if include_optional:
            return School(
                id = '',
                name = '',
                establishment_number = '',
                urn = 56,
                phase_of_education = '',
                la_code = '',
                timezone = '',
                mis = '',
                address = wonde.models.school_address.School_address(
                    address_line_1 = 'St James's Passage', 
                    address_line_2 = 'Duke's Place', 
                    address_town = 'London', 
                    address_postcode = 'EC3A 5DE', 
                    address_country = wonde.models.school_address_address_country.School_address_address_country(
                        code = 'GBR', 
                        name = 'United Kingdom', ), ),
                extended = wonde.models.school_extended.School_extended(
                    allows_writeback = True, 
                    has_timetables = True, 
                    has_lesson_attendance = True, ),
                region = wonde.models.school_region.School_region(
                    code = 'GBR', 
                    domain = 'api.wonde.com', 
                    school_url = 'https://api.wonde.com/v1.0/schools/A1300691890', 
                    identifiers = wonde.models.school_region_identifiers.School_region_identifiers(
                        la_code = '201', 
                        establishment_number = '3614', 
                        urn = 10000, ), )
            )
        else:
            return School(
        )
        """

    def testSchool(self):
        """Test School"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
