"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.student import Student


class TestStudent(unittest.TestCase):
    """Student unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Student:
        """Test Student
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Student`
        """
        model = Student()  # noqa: E501
        if include_optional:
            return Student(
                id = 'A1749191433',
                upi = '8d444684b7aa79bc97f8594a4aab7ce3',
                mis_id = '9919',
                initials = 'TS',
                surname = 'Smith',
                forename = 'Tom',
                middle_names = '',
                legal_surname = 'Smith',
                legal_forename = 'Tom',
                gender = 'MALE',
                date_of_birth = 'Thu Feb 11 00:00:00 UTC 2010',
                restored_at = wonde.models.date_time_object.DateTimeObject(
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timezone_type = 3, 
                    timezone = 'UTC', ),
                created_at = wonde.models.date_time_object.DateTimeObject(
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timezone_type = 3, 
                    timezone = 'UTC', ),
                updated_at = wonde.models.date_time_object.DateTimeObject(
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    timezone_type = 3, 
                    timezone = 'UTC', ),
                contact_details = wonde.models.employee_contact_details.Employee_contact_details(
                    data = wonde.models.contact_details.ContactDetails(
                        emails = wonde.models.contact_details_emails.ContactDetails_emails(
                            email = '', ), ), ),
                education_details = wonde.models.student_education_details.Student_education_details(
                    data = wonde.models.education_details.EducationDetails(
                        current_nc_year = '', 
                        local_upn = '', ), )
            )
        else:
            return Student(
        )
        """

    def testStudent(self):
        """Test Student"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
