"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest


class TestMetaSchoolsSchoolIdGet200Response(unittest.TestCase):
    """MetaSchoolsSchoolIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MetaSchoolsSchoolIdGet200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MetaSchoolsSchoolIdGet200Response`
        """
        model = wonde.models.meta_schools_school_id_get200_response.MetaSchoolsSchoolIdGet200Response()  # noqa: E501
        if include_optional :
            return MetaSchoolsSchoolIdGet200Response(
                data = wonde.models.school_meta.SchoolMeta(
                    online = True, 
                    approved = True, 
                    audited = True, 
                    custom_attendance_codes = True, )
            )
        else :
            return MetaSchoolsSchoolIdGet200Response(
        )
        """

    def testMetaSchoolsSchoolIdGet200Response(self):
        """Test MetaSchoolsSchoolIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
