"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.api.employees_api import EmployeesApi


class TestEmployeesApi(unittest.TestCase):
    """EmployeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeesApi()

    def tearDown(self) -> None:
        pass

    def test_get_school_employee(self) -> None:
        """Test case for get_school_employee

        Get specific employee for a school  # noqa: E501
        """
        pass

    def test_list_school_employees(self) -> None:
        """Test case for list_school_employees

        Get all employees for a school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
