"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.api.deletions_api import DeletionsApi


class TestDeletionsApi(unittest.TestCase):
    """DeletionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeletionsApi()

    def tearDown(self) -> None:
        pass

    def test_list_school_deletions(self) -> None:
        """Test case for list_school_deletions

        Get deletions for a school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
