"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.school_region_identifiers import SchoolRegionIdentifiers


class TestSchoolRegionIdentifiers(unittest.TestCase):
    """SchoolRegionIdentifiers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchoolRegionIdentifiers:
        """Test SchoolRegionIdentifiers
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchoolRegionIdentifiers`
        """
        model = SchoolRegionIdentifiers()  # noqa: E501
        if include_optional:
            return SchoolRegionIdentifiers(
                la_code = '201',
                establishment_number = '3614',
                urn = 10000
            )
        else:
            return SchoolRegionIdentifiers(
        )
        """

    def testSchoolRegionIdentifiers(self):
        """Test SchoolRegionIdentifiers"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
