"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.api.lessons_api import LessonsApi


class TestLessonsApi(unittest.TestCase):
    """LessonsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LessonsApi()

    def tearDown(self) -> None:
        pass

    def test_get_school_lesson(self) -> None:
        """Test case for get_school_lesson

        Returns a specific lesson for a specific school  # noqa: E501
        """
        pass

    def test_list_school_lessons(self) -> None:
        """Test case for list_school_lessons

        Returns a list of lessons for a specific school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
