"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.list_school_subjects200_response import (
    ListSchoolSubjects200Response,
)


class TestListSchoolSubjects200Response(unittest.TestCase):
    """ListSchoolSubjects200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSchoolSubjects200Response:
        """Test ListSchoolSubjects200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ListSchoolSubjects200Response`
        """
        model = ListSchoolSubjects200Response()  # noqa: E501
        if include_optional:
            return ListSchoolSubjects200Response(
                data = [
                    wonde.models.subject.Subject(
                        id = 'A1362597725', 
                        mis_id = '520', 
                        code = 'Bi', 
                        name = 'Biology', 
                        active = True, 
                        created_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), 
                        updated_at = wonde.models.date_time_object.DateTimeObject(
                            date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            timezone_type = 3, 
                            timezone = 'UTC', ), )
                    ],
                meta = wonde.models.meta.Meta(
                    pagination = wonde.models.pagination.Pagination(
                        next = 'https://api.wonde.com/v1.0/schools/{school_id}/students/?page=2', 
                        previous = '', 
                        more = True, 
                        per_page = 2, 
                        current_page = 1, ), 
                    includes = [
                        ''
                        ], )
            )
        else:
            return ListSchoolSubjects200Response(
        )
        """

    def testListSchoolSubjects200Response(self):
        """Test ListSchoolSubjects200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
