"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.school_address import SchoolAddress


class TestSchoolAddress(unittest.TestCase):
    """SchoolAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchoolAddress:
        """Test SchoolAddress
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchoolAddress`
        """
        model = SchoolAddress()  # noqa: E501
        if include_optional:
            return SchoolAddress(
                address_line_1 = 'St James's Passage',
                address_line_2 = 'Duke's Place',
                address_town = 'London',
                address_postcode = 'EC3A 5DE',
                address_country = wonde.models.school_address_address_country.School_address_address_country(
                    code = 'GBR', 
                    name = 'United Kingdom', )
            )
        else:
            return SchoolAddress(
        )
        """

    def testSchoolAddress(self):
        """Test SchoolAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
