"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

import wonde


class TestDeletionsApi(unittest.TestCase):
    """DeletionsApi unit test stubs"""

    def setUp(self):
        self.api = wonde.api.deletions_api.DeletionsApi()

    def tearDown(self):
        pass

    def test_schools_school_id_deletions_get(self):
        """Test case for schools_school_id_deletions_get

        Get deletions for a school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
