"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

import wonde


class TestSchoolsApi(unittest.TestCase):
    """SchoolsApi unit test stubs"""

    def setUp(self):
        self.api = wonde.api.schools_api.SchoolsApi()

    def tearDown(self):
        pass

    def test_get_school(self):
        """Test case for get_school

        Retrieve a specific school  # noqa: E501
        """
        pass

    def test_meta_schools_school_id_acl_get(self):
        """Test case for meta_schools_school_id_acl_get

        Retrieve the access control list applied to a school  # noqa: E501
        """
        pass

    def test_meta_schools_school_id_get(self):
        """Test case for meta_schools_school_id_get

        Retrieve meta data for a school  # noqa: E501
        """
        pass

    def test_meta_schools_school_id_permissions_get(self):
        """Test case for meta_schools_school_id_permissions_get

        Retrieve the permissions applied to a school  # noqa: E501
        """
        pass

    def test_schools_all_get(self):
        """Test case for schools_all_get

        Retrieve all schools  # noqa: E501
        """
        pass

    def test_schools_approved_get(self):
        """Test case for schools_approved_get

        Retrieve all approved schools  # noqa: E501
        """
        pass

    def test_schools_audited_get(self):
        """Test case for schools_audited_get

        Retrieve all audited schools  # noqa: E501
        """
        pass

    def test_schools_declined_get(self):
        """Test case for schools_declined_get

        Retrieve all schools with declined access  # noqa: E501
        """
        pass

    def test_schools_offline_get(self):
        """Test case for schools_offline_get

        Retrieve all offline schools  # noqa: E501
        """
        pass

    def test_schools_pending_get(self):
        """Test case for schools_pending_get

        Retrieve all schools with pending access request  # noqa: E501
        """
        pass

    def test_schools_revoked_get(self):
        """Test case for schools_revoked_get

        Retrieve all schools with revoked access  # noqa: E501
        """
        pass

    def test_schools_school_id_request_access_post(self):
        """Test case for schools_school_id_request_access_post

        Request access to a school  # noqa: E501
        """
        pass

    def test_schools_school_id_revoke_access_delete(self):
        """Test case for schools_school_id_revoke_access_delete

        Revoke access to a school  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
