"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.employee_employment_details import EmployeeEmploymentDetails


class TestEmployeeEmploymentDetails(unittest.TestCase):
    """EmployeeEmploymentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmployeeEmploymentDetails:
        """Test EmployeeEmploymentDetails
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EmployeeEmploymentDetails`
        """
        model = EmployeeEmploymentDetails()  # noqa: E501
        if include_optional:
            return EmployeeEmploymentDetails(
                data = wonde.models.employment_details.EmploymentDetails(
                    current = True, 
                    teaching_staff = True, 
                    employment_start_date = wonde.models.date_time_object.DateTimeObject(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        timezone_type = 3, 
                        timezone = 'UTC', ), 
                    employment_end_date = wonde.models.date_time_object.DateTimeObject(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        timezone_type = 3, 
                        timezone = 'UTC', ), 
                    role_text = '', )
            )
        else:
            return EmployeeEmploymentDetails(
        )
        """

    def testEmployeeEmploymentDetails(self):
        """Test EmployeeEmploymentDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
