"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest


class TestSchoolExtended(unittest.TestCase):
    """SchoolExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SchoolExtended
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchoolExtended`
        """
        model = wonde.models.school_extended.SchoolExtended()  # noqa: E501
        if include_optional :
            return SchoolExtended(
                allows_writeback = True, 
                has_timetables = True, 
                has_lesson_attendance = True
            )
        else :
            return SchoolExtended(
        )
        """

    def testSchoolExtended(self):
        """Test SchoolExtended"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
