"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest

from wonde.models.school_region import SchoolRegion


class TestSchoolRegion(unittest.TestCase):
    """SchoolRegion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchoolRegion:
        """Test SchoolRegion
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchoolRegion`
        """
        model = SchoolRegion()  # noqa: E501
        if include_optional:
            return SchoolRegion(
                code = 'GBR',
                domain = 'api.wonde.com',
                school_url = 'https://api.wonde.com/v1.0/schools/A1300691890',
                identifiers = wonde.models.school_region_identifiers.School_region_identifiers(
                    la_code = '201', 
                    establishment_number = '3614', 
                    urn = 10000, )
            )
        else:
            return SchoolRegion(
        )
        """

    def testSchoolRegion(self):
        """Test SchoolRegion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
