"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


import unittest


class TestSchoolsSchoolIdClassesClassIdGet200Response(unittest.TestCase):
    """SchoolsSchoolIdClassesClassIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SchoolsSchoolIdClassesClassIdGet200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SchoolsSchoolIdClassesClassIdGet200Response`
        """
        model = wonde.models.schools_school_id_classes_class_id_get200_response.SchoolsSchoolIdClassesClassIdGet200Response()  # noqa: E501
        if include_optional :
            return SchoolsSchoolIdClassesClassIdGet200Response(
                data = wonde.models.class.Class(
                    id = 'A1329183376', 
                    mis_id = '8925', 
                    name = '10A/Ar1', 
                    code = '10A/Ar1', 
                    description = '10A/Ar1', 
                    subject = 'Mathematics', 
                    alternative = False, 
                    restored_at = wonde.models.date_time_object.DateTimeObject(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        timezone_type = 3, 
                        timezone = 'UTC', ), 
                    created_at = wonde.models.date_time_object.DateTimeObject(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        timezone_type = 3, 
                        timezone = 'UTC', ), 
                    updated_at = , ), 
                meta = wonde.models.meta.Meta(
                    pagination = wonde.models.pagination.Pagination(
                        next = 'https://api.wonde.com/v1.0/schools/{school_id}/students/?page=2', 
                        previous = '', 
                        more = True, 
                        per_page = 2, 
                        current_page = 1, ), 
                    includes = [
                        ''
                        ], )
            )
        else :
            return SchoolsSchoolIdClassesClassIdGet200Response(
        )
        """

    def testSchoolsSchoolIdClassesClassIdGet200Response(self):
        """Test SchoolsSchoolIdClassesClassIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
