"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from setuptools import find_packages, setup

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = 'pywonde'
VERSION = '0.1.0'
PYTHON_REQUIRES = '>= 3.10'
REQUIRES = [
    'urllib3 >= 2.6.3, < 3.0.0',
    'python-dateutil >= 2.8.2',
    'pydantic >= 2.11',
    'typing-extensions >= 4.7.1',
]

setup(
    name=NAME,
    version=VERSION,
    description='Wonde API',
    author='OpenAPI Generator community',
    author_email='team@openapitools.org',
    url='https://github.com/Edrolo/pywonde',
    keywords=['OpenAPI', 'OpenAPI-Generator', 'Wonde API'],
    install_requires=REQUIRES,
    packages=find_packages(exclude=['test', 'tests']),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    API Docs
    """,
    package_data={'wonde': ['py.typed']},
)
