# coding: utf-8

# flake8: noqa

"""
Wonde API

API Docs  # noqa: E501

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


__version__ = '0.1.0'

# import apis into sdk package
from wonde.api.classes_api import ClassesApi
from wonde.api.deletions_api import DeletionsApi
from wonde.api.employees_api import EmployeesApi
from wonde.api.lessons_api import LessonsApi
from wonde.api.schools_api import SchoolsApi
from wonde.api.students_api import StudentsApi
from wonde.api.subjects_api import SubjectsApi

# import ApiClient
from wonde.api_response import ApiResponse
from wonde.api_client import ApiClient
from wonde.configuration import Configuration
from wonde.exceptions import OpenApiException
from wonde.exceptions import ApiTypeError
from wonde.exceptions import ApiValueError
from wonde.exceptions import ApiKeyError
from wonde.exceptions import ApiAttributeError
from wonde.exceptions import ApiException

# import models into sdk package
from wonde.models.class_lessons import ClassLessons
from wonde.models.class_students import ClassStudents
from wonde.models.class_subject import ClassSubject
from wonde.models.class_subject_one_of import ClassSubjectOneOf
from wonde.models.contact import Contact
from wonde.models.date_time_object import DateTimeObject
from wonde.models.deletion import Deletion
from wonde.models.employee import Employee
from wonde.models.get_school_lessons200_response import GetSchoolLessons200Response
from wonde.models.get_school_lessons200_response_meta import GetSchoolLessons200ResponseMeta
from wonde.models.get_subjects200_response import GetSubjects200Response
from wonde.models.lesson import Lesson
from wonde.models.list_students200_response import ListStudents200Response
from wonde.models.meta import Meta
from wonde.models.meta_schools_school_id_get200_response import MetaSchoolsSchoolIdGet200Response
from wonde.models.meta_schools_school_id_permissions_get200_response import (
    MetaSchoolsSchoolIdPermissionsGet200Response,
)
from wonde.models.model_class import ModelClass
from wonde.models.pagination import Pagination
from wonde.models.permission import Permission
from wonde.models.school import School
from wonde.models.school_address import SchoolAddress
from wonde.models.school_address_address_country import SchoolAddressAddressCountry
from wonde.models.school_extended import SchoolExtended
from wonde.models.school_meta import SchoolMeta
from wonde.models.school_region import SchoolRegion
from wonde.models.school_region_identifiers import SchoolRegionIdentifiers
from wonde.models.schools_all_get200_response import SchoolsAllGet200Response
from wonde.models.schools_school_id_classes_class_id_get200_response import (
    SchoolsSchoolIdClassesClassIdGet200Response,
)
from wonde.models.schools_school_id_classes_get200_response import (
    SchoolsSchoolIdClassesGet200Response,
)
from wonde.models.schools_school_id_deletions_get200_response import (
    SchoolsSchoolIdDeletionsGet200Response,
)
from wonde.models.schools_school_id_employees_get200_response import (
    SchoolsSchoolIdEmployeesGet200Response,
)
from wonde.models.schools_school_id_request_access_post200_response import (
    SchoolsSchoolIdRequestAccessPost200Response,
)
from wonde.models.schools_school_id_request_access_post_request import (
    SchoolsSchoolIdRequestAccessPostRequest,
)
from wonde.models.student import Student
from wonde.models.subject import Subject
