"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class Contact(BaseModel):
    """
    Contact
    """

    first_name: Optional[StrictStr] = Field(default=None, description='First name of contact')
    last_name: Optional[StrictStr] = Field(default=None, description='Last name of contact')
    phone_number: Optional[StrictStr] = Field(default=None, description='Phone number of contact')
    email_address: Optional[StrictStr] = Field(default=None, description='Email address of contact')
    notes: Optional[StrictStr] = Field(default=None, description='Notes for the contact')
    __properties: ClassVar[List[str]] = [
        'first_name',
        'last_name',
        'phone_number',
        'email_address',
        'notes',
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Contact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Contact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'first_name': obj.get('first_name'),
                'last_name': obj.get('last_name'),
                'phone_number': obj.get('phone_number'),
                'email_address': obj.get('email_address'),
                'notes': obj.get('notes'),
            }
        )
        return _obj
