"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class DateTimeObject(BaseModel):
    """
    DateTimeObject
    """

    var_date: Optional[datetime] = Field(
        default=None,
        description='The date and time value, apparently with no timezone',
        alias='date',
    )
    timezone_type: Optional[StrictInt] = Field(
        default=None,
        description='The type of the timezone, represented by an integer. Not sure of mapping.',
        json_schema_extra={'examples': [3]},
    )
    timezone: Optional[StrictStr] = Field(
        default=None,
        description='The timezone in which the date and time is represented.',
        json_schema_extra={'examples': ['UTC']},
    )
    __properties: ClassVar[List[str]] = ['date', 'timezone_type', 'timezone']

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DateTimeObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DateTimeObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'date': obj.get('date'),
                'timezone_type': obj.get('timezone_type'),
                'timezone': obj.get('timezone'),
            }
        )
        return _obj
