"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from wonde.models.date_time_object import DateTimeObject


class Deletion(BaseModel):
    """
    Deletion
    """

    type: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    mis_id: Optional[StrictStr] = None
    deleted_at: Optional[DateTimeObject] = None
    restored_at: Optional[DateTimeObject] = None
    __properties: ClassVar[List[str]] = ['type', 'id', 'mis_id', 'deleted_at', 'restored_at']

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Deletion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deleted_at
        if self.deleted_at:
            _dict['deleted_at'] = self.deleted_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of restored_at
        if self.restored_at:
            _dict['restored_at'] = self.restored_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Deletion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'type': obj.get('type'),
                'id': obj.get('id'),
                'mis_id': obj.get('mis_id'),
                'deleted_at': DateTimeObject.from_dict(obj['deleted_at'])
                if obj.get('deleted_at') is not None
                else None,
                'restored_at': DateTimeObject.from_dict(obj['restored_at'])
                if obj.get('restored_at') is not None
                else None,
            }
        )
        return _obj
