"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from wonde.models.date_time_object import DateTimeObject


class EmploymentDetails(BaseModel):
    """
    EmploymentDetails
    """

    current: Optional[StrictBool] = None
    teaching_staff: Optional[StrictBool] = None
    employment_start_date: Optional[DateTimeObject] = None
    employment_end_date: Optional[DateTimeObject] = None
    role_text: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        'current',
        'teaching_staff',
        'employment_start_date',
        'employment_end_date',
        'role_text',
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmploymentDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of employment_start_date
        if self.employment_start_date:
            _dict['employment_start_date'] = self.employment_start_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of employment_end_date
        if self.employment_end_date:
            _dict['employment_end_date'] = self.employment_end_date.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmploymentDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'current': obj.get('current'),
                'teaching_staff': obj.get('teaching_staff'),
                'employment_start_date': DateTimeObject.from_dict(obj['employment_start_date'])
                if obj.get('employment_start_date') is not None
                else None,
                'employment_end_date': DateTimeObject.from_dict(obj['employment_end_date'])
                if obj.get('employment_end_date') is not None
                else None,
                'role_text': obj.get('role_text'),
            }
        )
        return _obj
