"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from wonde.models.date_time_object import DateTimeObject
from wonde.models.employee_contact_details import EmployeeContactDetails
from wonde.models.employee_employment_details import EmployeeEmploymentDetails


class Employee(BaseModel):
    """
    Employee
    """

    id: Optional[StrictStr] = Field(
        default=None,
        description='The ID of the object.',
        json_schema_extra={'examples': ['A1329183376']},
    )
    upi: Optional[StrictStr] = Field(
        default=None,
        description='Unique Person Identifier - If a person is a contact and an employee they will have the same UPI but different ids.',
        json_schema_extra={'examples': ['5cc4ab015f8f7870b581e30e0ef474fa']},
    )
    mis_id: Optional[StrictStr] = Field(
        default=None,
        description='The ID in the Management Information System (MIS).',
        json_schema_extra={'examples': ['26']},
    )
    title: Optional[StrictStr] = Field(
        default=None, description="Employee's title.", json_schema_extra={'examples': ['Mrs']}
    )
    initials: Optional[StrictStr] = Field(
        default=None, description="Employee's initials.", json_schema_extra={'examples': ['SS']}
    )
    surname: Optional[StrictStr] = Field(
        default=None, description="Employee's surname.", json_schema_extra={'examples': ['Smith']}
    )
    forename: Optional[StrictStr] = Field(
        default=None, description="Employee's forename.", json_schema_extra={'examples': ['Sally']}
    )
    middle_names: Optional[StrictStr] = Field(
        default=None,
        description="Employee's middle names.",
        json_schema_extra={'examples': ['Victoria']},
    )
    legal_surname: Optional[StrictStr] = Field(
        default=None,
        description="Employee's legal surname.",
        json_schema_extra={'examples': ['Smith']},
    )
    legal_forename: Optional[StrictStr] = Field(
        default=None,
        description="Employee's legal forename.",
        json_schema_extra={'examples': ['Sally']},
    )
    gender: Optional[StrictStr] = Field(
        default=None,
        description="Employee's gender. (male|female)",
        json_schema_extra={'examples': ['female']},
    )
    date_of_birth: Optional[date] = Field(
        default=None,
        description="Employee's date of birth.",
        json_schema_extra={'examples': ['1963-02-11']},
    )
    restored_at: Optional[DateTimeObject] = None
    created_at: Optional[DateTimeObject] = None
    updated_at: Optional[DateTimeObject] = None
    contact_details: Optional[EmployeeContactDetails] = None
    employment_details: Optional[EmployeeEmploymentDetails] = None
    __properties: ClassVar[List[str]] = [
        'id',
        'upi',
        'mis_id',
        'title',
        'initials',
        'surname',
        'forename',
        'middle_names',
        'legal_surname',
        'legal_forename',
        'gender',
        'date_of_birth',
        'restored_at',
        'created_at',
        'updated_at',
        'contact_details',
        'employment_details',
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Employee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of restored_at
        if self.restored_at:
            _dict['restored_at'] = self.restored_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_at
        if self.created_at:
            _dict['created_at'] = self.created_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_at
        if self.updated_at:
            _dict['updated_at'] = self.updated_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_details
        if self.contact_details:
            _dict['contact_details'] = self.contact_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of employment_details
        if self.employment_details:
            _dict['employment_details'] = self.employment_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Employee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'id': obj.get('id'),
                'upi': obj.get('upi'),
                'mis_id': obj.get('mis_id'),
                'title': obj.get('title'),
                'initials': obj.get('initials'),
                'surname': obj.get('surname'),
                'forename': obj.get('forename'),
                'middle_names': obj.get('middle_names'),
                'legal_surname': obj.get('legal_surname'),
                'legal_forename': obj.get('legal_forename'),
                'gender': obj.get('gender'),
                'date_of_birth': obj.get('date_of_birth'),
                'restored_at': DateTimeObject.from_dict(obj['restored_at'])
                if obj.get('restored_at') is not None
                else None,
                'created_at': DateTimeObject.from_dict(obj['created_at'])
                if obj.get('created_at') is not None
                else None,
                'updated_at': DateTimeObject.from_dict(obj['updated_at'])
                if obj.get('updated_at') is not None
                else None,
                'contact_details': EmployeeContactDetails.from_dict(obj['contact_details'])
                if obj.get('contact_details') is not None
                else None,
                'employment_details': EmployeeEmploymentDetails.from_dict(obj['employment_details'])
                if obj.get('employment_details') is not None
                else None,
            }
        )
        return _obj
