"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class Pagination(BaseModel):
    """
    https://docs.wonde.com/docs/api/sync#pagination The pagination object is returned as part of the response body when pagination is enabled.  By default, 50 objects are returned per page. If the response contains 50 objects or fewer,  no pagination object will be returned. If the response contains more than 50 objects, the  first 50 will be returned along with the pagination object. You can request a different pagination limit or force pagination by appending ?per_page= to  the request with the number of items you would like per page. For instance, to show only two  results per page, you could add ?per_page=2 to the end of your query.  The maximum number of results per page is set per-endpoint.
    """

    next: Optional[StrictStr] = Field(
        default=None,
        description='The next page in the paginated response.',
        json_schema_extra={
            'examples': ['https://api.wonde.com/v1.0/schools/{school_id}/students/?page=2']
        },
    )
    previous: Optional[StrictStr] = Field(
        default=None, description='The previous page in the paginated response.'
    )
    more: Optional[StrictBool] = Field(
        default=None, description='Is there another page after the current page.'
    )
    per_page: Optional[StrictInt] = Field(
        default=None,
        description='How many rows are currently being returned per page/response.',
        json_schema_extra={'examples': [2]},
    )
    current_page: Optional[StrictInt] = Field(
        default=None,
        description='The current paginated page number.',
        json_schema_extra={'examples': [1]},
    )
    __properties: ClassVar[List[str]] = ['next', 'previous', 'more', 'per_page', 'current_page']

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Pagination from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Pagination from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'next': obj.get('next'),
                'previous': obj.get('previous'),
                'more': obj.get('more'),
                'per_page': obj.get('per_page'),
                'current_page': obj.get('current_page'),
            }
        )
        return _obj
