"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from wonde.models.date_time_object import DateTimeObject


class Permission(BaseModel):
    """
    Permission
    """

    identity: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    parent: Optional[StrictStr] = None
    group: Optional[StrictStr] = None
    active_from: Optional[DateTimeObject] = None
    optional: Optional[StrictBool] = None
    approved: Optional[StrictBool] = None
    audited: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = [
        'identity',
        'name',
        'description',
        'parent',
        'group',
        'active_from',
        'optional',
        'approved',
        'audited',
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Permission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of active_from
        if self.active_from:
            _dict['active_from'] = self.active_from.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Permission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'identity': obj.get('identity'),
                'name': obj.get('name'),
                'description': obj.get('description'),
                'parent': obj.get('parent'),
                'group': obj.get('group'),
                'active_from': DateTimeObject.from_dict(obj['active_from'])
                if obj.get('active_from') is not None
                else None,
                'optional': obj.get('optional'),
                'approved': obj.get('approved'),
                'audited': obj.get('audited'),
            }
        )
        return _obj
