"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from pydantic_core import to_jsonable_python
from typing_extensions import Self


class SchoolMeta(BaseModel):
    """
    SchoolMeta
    """

    online: Optional[StrictBool] = Field(default=None, description='If the school is online')
    approved: Optional[StrictBool] = Field(
        default=None, description='If the school has approved access to application'
    )
    audited: Optional[StrictBool] = Field(
        default=None, description='If the school has been audited for data completeness'
    )
    custom_attendance_codes: Optional[StrictBool] = Field(
        default=None, description='If the school has their own custom attendance codes'
    )
    __properties: ClassVar[List[str]] = ['online', 'approved', 'audited', 'custom_attendance_codes']

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchoolMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchoolMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'online': obj.get('online'),
                'approved': obj.get('approved'),
                'audited': obj.get('audited'),
                'custom_attendance_codes': obj.get('custom_attendance_codes'),
            }
        )
        return _obj
