"""
Wonde API

API Docs

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from wonde.models.date_time_object import DateTimeObject
from wonde.models.school_class_employees import SchoolClassEmployees
from wonde.models.school_class_lessons import SchoolClassLessons
from wonde.models.school_class_students import SchoolClassStudents
from wonde.models.school_class_subject import SchoolClassSubject


class SchoolClass(BaseModel):
    """
    https://docs.wonde.com/docs/api/sync#get-classes Related objects Name                            Relationship -------------------------------------------- subject                         one students                        many students.contact_details        many > one students.education_details      many > one students.extended_details       many > one students.house                  many > one students.registration           many > one students.year                   many > one students.boarding               many > one students.campus                 many > one employees                       many employees.contact_details       many > one employees.employment_details    many > one employees.extended_details      many > one lessons                         many lessons.room                    many > one lessons.period                  many > one
    """

    id: Optional[StrictStr] = Field(
        default=None,
        description='The ID of the object.',
        json_schema_extra={'examples': ['A1329183376']},
    )
    mis_id: Optional[StrictStr] = Field(
        default=None, description='The ID in the MIS.', json_schema_extra={'examples': ['8925']}
    )
    type: Optional[StrictStr] = Field(
        default=None,
        description='Class type. Australia region values: academic, duty, extra curricular, on call, roll class, rostered time off, staff meeting, study. ',
        json_schema_extra={'examples': ['academic']},
    )
    name: Optional[StrictStr] = Field(
        default=None, description='Class name.', json_schema_extra={'examples': ['10A/Ar1']}
    )
    code: Optional[StrictStr] = Field(
        default=None, description='Class code.', json_schema_extra={'examples': ['10A/Ar1']}
    )
    description: Optional[StrictStr] = Field(
        default=None, description='Class description.', json_schema_extra={'examples': ['10A/Ar1']}
    )
    subject: Optional[SchoolClassSubject] = None
    alternative: Optional[StrictBool] = Field(
        default=None,
        description='The class is an alternative to another class.',
        json_schema_extra={'examples': [False]},
    )
    priority: Optional[StrictBool] = Field(
        default=None,
        description='The class is a priority to another class. Supported in Edval and Timetabling Solutions data sync only. ',
        json_schema_extra={'examples': [False]},
    )
    academic_year: Optional[StrictStr] = Field(
        default=None,
        description='The academic year of the class. Supported in SIMS, Edumate API and Synergetic data sync only. ',
        json_schema_extra={'examples': ['2023']},
    )
    year_group: Optional[StrictStr] = Field(
        default=None,
        description='The year group of the class. Supported in SIMS only.',
        json_schema_extra={'examples': ['10']},
    )
    restored_at: Optional[DateTimeObject] = None
    created_at: Optional[DateTimeObject] = None
    updated_at: Optional[DateTimeObject] = None
    students: Optional[SchoolClassStudents] = None
    employees: Optional[SchoolClassEmployees] = None
    lessons: Optional[SchoolClassLessons] = None
    __properties: ClassVar[List[str]] = [
        'id',
        'mis_id',
        'type',
        'name',
        'code',
        'description',
        'subject',
        'alternative',
        'priority',
        'academic_year',
        'year_group',
        'restored_at',
        'created_at',
        'updated_at',
        'students',
        'employees',
        'lessons',
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchoolClass from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set()

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of subject
        if self.subject:
            _dict['subject'] = self.subject.to_dict()
        # override the default output from pydantic by calling `to_dict()` of restored_at
        if self.restored_at:
            _dict['restored_at'] = self.restored_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_at
        if self.created_at:
            _dict['created_at'] = self.created_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated_at
        if self.updated_at:
            _dict['updated_at'] = self.updated_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of students
        if self.students:
            _dict['students'] = self.students.to_dict()
        # override the default output from pydantic by calling `to_dict()` of employees
        if self.employees:
            _dict['employees'] = self.employees.to_dict()
        # override the default output from pydantic by calling `to_dict()` of lessons
        if self.lessons:
            _dict['lessons'] = self.lessons.to_dict()
        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and 'type' in self.model_fields_set:
            _dict['type'] = None

        # set to None if alternative (nullable) is None
        # and model_fields_set contains the field
        if self.alternative is None and 'alternative' in self.model_fields_set:
            _dict['alternative'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and 'priority' in self.model_fields_set:
            _dict['priority'] = None

        # set to None if academic_year (nullable) is None
        # and model_fields_set contains the field
        if self.academic_year is None and 'academic_year' in self.model_fields_set:
            _dict['academic_year'] = None

        # set to None if year_group (nullable) is None
        # and model_fields_set contains the field
        if self.year_group is None and 'year_group' in self.model_fields_set:
            _dict['year_group'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchoolClass from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'id': obj.get('id'),
                'mis_id': obj.get('mis_id'),
                'type': obj.get('type'),
                'name': obj.get('name'),
                'code': obj.get('code'),
                'description': obj.get('description'),
                'subject': SchoolClassSubject.from_dict(obj['subject'])
                if obj.get('subject') is not None
                else None,
                'alternative': obj.get('alternative'),
                'priority': obj.get('priority'),
                'academic_year': obj.get('academic_year'),
                'year_group': obj.get('year_group'),
                'restored_at': DateTimeObject.from_dict(obj['restored_at'])
                if obj.get('restored_at') is not None
                else None,
                'created_at': DateTimeObject.from_dict(obj['created_at'])
                if obj.get('created_at') is not None
                else None,
                'updated_at': DateTimeObject.from_dict(obj['updated_at'])
                if obj.get('updated_at') is not None
                else None,
                'students': SchoolClassStudents.from_dict(obj['students'])
                if obj.get('students') is not None
                else None,
                'employees': SchoolClassEmployees.from_dict(obj['employees'])
                if obj.get('employees') is not None
                else None,
                'lessons': SchoolClassLessons.from_dict(obj['lessons'])
                if obj.get('lessons') is not None
                else None,
            }
        )
        return _obj
